--create database test
--on
--(
--	name = test_db,
--	filename = 'G:\Ali\Database Lab\test_db1.mdf',
--	size = 20,
--	maxsize = 100,
--	filegrowth = 5
--)
--log on
--(
--	name = test_log,
--	filename = 'G:\Ali\Database Lab\test_log.ldf',
--	size = 10,
--	maxsize = 50,
--	filegrowth = 5	
--)